{{- $image := printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gopher-cni.fullname" . }}
  labels:
    {{- include "gopher-cni.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gopher-cni.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gopher-cni.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gopher-cni.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: gopher-cni-daemon
        image: "{{ $image }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - daemon
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: LOG_FORMAT
          value: {{ .Values.logFormat }}
        - name: MOUNTED_HOST_DIR
          value: {{ .Values.cni.containerHostPathPrefix }}
        - name: CNI_NET_DIR
          value: {{ .Values.cni.host.cniNetDir }}
        - name: CNI_BIN_TARGET_DIR
          value: {{ .Values.cni.host.binPath}}
        - name: UDS_SOCKET_ADDRESS
          value: {{ printf "%s/log.sock" .Values.cni.host.udsSocketDir }}
        - name: WEBHOOK_IMAGE
          value: {{ .Values.webhook.injectedImage | default $image | quote }}
        - name: WEBHOOK_PORT
          value: {{ .Values.webhook.port | quote }}
        - name: WEBHOOK_TLS_CERT_PATH
          value: {{ .Values.webhook.tls.certPath }}
        - name: WEBHOOK_TLS_KEY_PATH
          value: {{ .Values.webhook.tls.keyPath }}
        ports:
        - name: webhook
          containerPort: {{ .Values.webhook.port }}
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          # Run as root to allow the CNI plugin to write to the host CNI directory
          runAsUser: 0
          {{- with .Values.securityContext }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: certs
          mountPath: /etc/webhook/certs
          readOnly: true
        - name: cni-bin
          mountPath: {{ printf "%s/%s" .Values.cni.containerHostPathPrefix ( trimPrefix "/" .Values.cni.host.binPath )  }}
        - name: cni-config
          mountPath: {{ printf "%s/%s" .Values.cni.containerHostPathPrefix ( trimPrefix "/" .Values.cni.host.cniNetDir )  }}
        - name: uds-socket
          mountPath: {{ printf "%s/%s" .Values.cni.containerHostPathPrefix ( trimPrefix "/" .Values.cni.host.udsSocketDir )  }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: certs
        secret:
          secretName: {{ include "gopher-cni.certificateSecretName" . }}
          defaultMode: 0640
      - name: cni-bin
        hostPath:
          path: {{ .Values.cni.host.binPath }}
          type: Directory
      - name: cni-config
        hostPath:
          path: {{ .Values.cni.host.cniNetDir }}
          type: Directory
      - name: uds-socket
        hostPath:
          path: {{ .Values.cni.host.udsSocketDir }}
          type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
