apiVersion: v2
name: gopher-cni
description: Kubernetes CNI plugin for WireGuard VPN tunneling
type: application
version: 0.7.0
appVersion: "0.7.0"
keywords:
  - cni
  - wireguard
  - vpn
  - tunneling
  - networking
  - container-networking
  - kubernetes
  - nat-pmp
  - port-forwarding
  - admission-webhook
home: https://github.com/bartlettc22/gopher-cni
sources:
  - https://github.com/bartlettc22/gopher-cni
maintainers:
  - name: bartlettc22
    url: https://github.com/bartlettc22
